default: styles/mastodon-bird-ui-dark.scss
mastodon-bird-ui-light: styles/mastodon-bird-ui-light.scss
mastodon-bird-ui-contrast: styles/mastodon-bird-ui-contrast.scss
mastodon-dark: styles/application.scss
mastodon-light: styles/mastodon-light.scss
contrast: styles/contrast.scss
modern-dark: styles/modern-dark.scss
modern-light: styles/modern-light.scss
tangerineui: styles/tangerineui.scss
tangerineui-purple: styles/tangerineui-purple.scss
tangerineui-pink: styles/tangerineui-pink.scss
tangerineui-shark: styles/tangerineui-shark.scss
tangerineui-shark-light: styles/tangerineui-shark-light.scss