default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
modern-dark: styles/modern-dark.scss
<<<<<<< HEAD
modern-light: styles/modern-light.scss
bird-light: styles/Bird-UI-light.scss
bird-dark: styles/Bird-UI-dark.scss
bird-contrast: styles/Bird-UI-contrast.scss
tangerineui: styles/tangerineui.scss
tangerineui-purple: styles/tangerineui-purple.scss
=======
modern-light: styles/modern-light.scss
>>>>>>> parent of 1389a76cd (Add theme: mastodon-bird-ui)
