name: Build container image
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    paths:
      - .github/workflows/build-image.yml
      - Dockerfile
permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate version metadata
        id: version_vars
        if: github.repository == 'shark85671/mastodon' && github.event_name == 'push' && github.ref_name == 'main'
        run: |
          echo mastodon_version_metadata=-$(date +'%Y%m%d') >> $GITHUB_OUTPUT
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mastodon:v4.3.0.1 , ${{ secrets.DOCKERHUB_USERNAME }}/mastodon:latest
          build-args: MASTODON_VERSION_METADATA=${{ steps.version_vars.outputs.mastodon_version_metadata }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
